# Generated by Django 4.0.3 on 2022-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinguser',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitinguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='waitinguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
