# Generated by Django 4.0.3 on 2022-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_waitinguser_born_alter_waitinguser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
