# Generated by Django 4.0.3 on 2022-04-11 12:18

import ROBOWEB.first.validatros
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_profile_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinguser',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[ROBOWEB.first.validatros.validator_min_lenght]),
        ),
    ]
